### ISSUE TITLE
Usage

### ISSUE THREAD

**Issue by ganesh-papola** [hamdiwanis/react-native-circular-picker#1]
Hii, How to use this in react native app. is it available in NPM?

**Comment by hamdiwanis** [comment]
hey @ganeshSinghSmartData thanks for your interest. but i actually did not have the time to publish it to npm yet , and i was waiting to see if someone would want to use it in first place :)

**Comment by ganeshSinghSmartData** [comment]
Great, actually i was implementing it in my project but  facing some issues like `'parentNode' is a required parameter` or `Exception thrown while executing UI block:- [CircularPickerView setColor:]: ...

my swift-View file's get or set functions are not being called.. any help?
Thanks

**Comment by hamdiwanis** [comment]
hey @ganeshSinghSmartData  got a notification of you replying but now i can't find it, was the problem solved?

**Comment by ganesh-papola** [comment]
Hii @hamdiwanis , 
Thanks for confirmation. The issue is resolved now, I have changed swift version to 3 now its working.
Thanks
